### ISSUE TITLE
DB queries crashing

### ISSUE THREAD

**Issue by Rochet2** [BlackWolfsDen/Eluna-Grumboz_VIP_System-Complete#1]
You are forcing the users to have "auth" as the DB name in your SQL queries.
If they have a different DB name the queries crash.
https://github.com/BlackWolfsDen/Eluna-Grumboz_VIP_System-Complete/blob/e6167a37d7d2a2caa5f9a7d0345288f04b539ab0/VIP_1_Core.ext#L56

I recommend removing the `auth.` from your SQL queries and changing `WorldDBQuery` to `AuthDBQuery` so the queries go to the correct DB automatically without specifying it in the query itself.

http://www.elunaengine.com/?search=DBQuery
http://www.elunaengine.com/?search=DBExecute

**Comment by BlackWolfsDen** [comment]
0.o ooohh yea good idea I will fix tonite or this weekend ;)

**Comment by BlackWolfsDen** [comment]
k updated the Engine to use AuthDBxxx . sorry guyz it took so long but i work during the summer and script in the winter ;)

**Comment by Rochet2** [comment]
done I guess?

**Comment by BlackWolfsDen** [comment]
tweeked it some more to support the reload eluna command. had some other issues float to the surface with Item_require_Vip so fixed it too lol fingers crossed , it seems to work for me now when players login after a reload eluna command or when logged in during a reload eluna.
yea i did update the DBQueries to the proper DB names lol ghaa i was sucha noob rofl
